@WebApiTest_HostAddress = http://localhost:5161

GET {{WebApiTest_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{WebApiTest_HostAddress}}/api/categories
Accept: application/json

###

GET {{WebApiTest_HostAddress}}/api/categories?searchValue=apple
Accept: application/json

###

POST {{WebApiTest_HostAddress}}/api/categories
Content-Type: application/json

{  
        "name" : "Apple",
        "description" : "Any kind of phone"
}

###

PUT {{WebApiTest_HostAddress}}/api/categories/232182eb-ddef-47e7-b258-5f8f5b5fd7fe
Content-type: application/json

{
  "name" : "Vivo",
  "description" : "very gooood"
}


###

DELETE {{WebApiTest_HostAddress}}/api/categories/232182eb-ddef-47e7-b258-5f8f5b5fd7fe
Content-type: application/json
